### ISSUE TITLE
tick of 0s causes deadlock

### ISSUE THREAD

**Issue by abraithwaite** [yields/phony#11]

**Comment by abraithwaite** [comment]
Deadlock causes a panic.  New implementation causes a panic.  Seems like something could be handled more cleanly in the implementation.

**Comment by yields** [comment]
hmm, can you elaborate?

```
  phony (master) go run main.go --tick 0
phony: --tick must be a positive interval, got "0s"
exit status 1
```

**Comment by abraithwaite** [comment]
Ah, I missed the other PR:

https://github.com/yields/phony/pull/13
